package:
  name: oceanicu
  version: 0.2

source:
  - git_url: https://github.com/gotm-model/code.git
    folder: gotm
    git_rev: v6.0
  - git_url: https://github.com/fabm-model/fabm.git
    git_depth: 1
    folder: fabm
  - git_url: https://github.com/BoldingBruggeman/fabm-mops.git
    git_depth: 1
    folder: mops
  - git_url: https://github.com/inogs/bfmforfabm
    git_rev: dev_monospectral
    folder: ogs
  - git_url: https://github.com/pmlmodelling/ersem
    git_depth: 1
    folder: ersem
  - git_url: https://github.com/BoldingBruggeman/fabm-pisces.git
    git_depth: 1
    folder: pisces

build:
  entry_points:
    - pyncview = pyncview.pyncview:main
    - multiplot = pyncview.multiplot:main

requirements:
  host:
    - netcdf-fortran             # [not win] not needed on Windows because it gets netcdf from GOTM
    - python
    - pip
  build:
    - cmake
    - make                       # [not win]
    - {{ compiler('c') }}        # [win] essential for Visual Studio + ifort, to find MSBuild!
    - {{ compiler('fortran') }}  # [not win]
  run:
    - python
    - numpy
    - matplotlib
    - netCDF4
    - pyqt

test:
  commands:
    - gotm -v
    - multiplot --version

about:
  summary: GOTM-FABM for OceanICU hands-on model workshop
  description: |
    The GOTM-FABM water column model, compiled with biogeochemical
    models used within OceanICU (MOPS, ERSEM, BFM). PyNcView
    is included for visualization of model results.
  license: GPL
  dev_url: https://github.com/BoldingBruggeman/oceanicu-fabm-workshop
